project_id = "jflmhdazpdtllucwpdxl"

[functions.admin-users]
verify_jwt = false

[functions.notion-images]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false

[functions.refresh-image]
verify_jwt = false

[functions.notion-image-upload]
verify_jwt = false
